import imgone from "../../../../assets/How/1st.png";
import imgTwo from "../../../../assets/How/2nd.png";
import imgThree from "../../../../assets/How/3rd.png";
import "./style.css";

const HowItWork = () => {
  return (
    <div className="timeline max-w-screen-xl mx-auto font-alice h-[100%] mt-[80px]">
      <h1 className="text-[38px] font-normal text-center mb-[32px] ">
        How It Work
      </h1>
      <p className="text-[18px]  font-normal text-center  max-w-[685px] mx-auto leading-[27px]">
        matrimony is process is simple. Create a profile with your
        preferences. Our AI generates personalized matches. Engage with
        potential partners your way. Build connections that matter. Your
        journey to a meaningful relationship starts here.
      </p>
      {/* cards */}
      <div data-aos="fade-right" data-aos-duration="2000" className="cards max-w-md mx-auto ">
        <div className="cards_body">
          <img src={imgone} alt="" className="mb-32" />
        </div>
      </div>
      {/* cards-2 */}
      <div data-aos="fade-left" data-aos-duration="2000" className="cards max-w-md mx-auto">
        <div className="cards_body text-left">
          <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932]">
            Select based on Interests, Location, and other pertinent filters.
          </h1>
          <p className="text-[18px] font-normal leading-[27px]">
            Discover your life partner on our matrimonial website, where
            interests align and love blossoms. Tailored to your location and
            preferences, find meaningful connections that last a lifetime
          </p>
        </div>
      </div>
      {/* cards-3 */}
      <div data-aos="fade-right" data-aos-duration="2000" className="cards max-w-md mx-auto">
        <div className="cards_body text-right">
          <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932]">
            Engage with your matches in the manner that suits you best
          </h1>
          <p className="text-[18px] font-normal leading-[27px]">
            Communicate on your terms with potential matches on our matrimonial
            website, Matrimony. Whether it is through messages, chats, or video
            calls, forge genuine connections in a way that feels comfortable for
            you.
          </p>
        </div>
      </div>
      {/* cards-4 */}
      <div data-aos="fade-left" data-aos-duration="2000" className="cards  max-w-md mx-auto">
        <div className="cards_body">
          <img src={imgTwo} alt=""/>
        </div>
      </div>
      {/* cards-5 */}
      <div data-aos="fade-right" data-aos-duration="2000" className="cards max-w-md mx-auto ">
        <div className="cards_body">
          <img src={imgThree} alt="" className="mb-10" />
        </div>
      </div>
      {/* cards-6 */}
      <div className="cards max-w-md mx-auto">
        <div data-aos="fade-left" data-aos-duration="2000" className="cards_body text-left">
          <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932]">
            Personalized match suggestions generated by AI to align with your
            preferences
          </h1>
          <p className="text-[18px] font-normal leading-[27px]">
            Where AI-driven precision meets matters of the heart. Our platform
            delivers tailor-made match suggestions, finely tuned to your
            desires, creating a journey to love that is as unique as you are
          </p>
        </div>
      </div>

      {/* cards-end */}

      {/* small device screen */}
      {/* cards */}
      {/* section */}
      <div data-aos="fade-right"  data-aos-duration="1500"  className="sec md:flex items-center justify-between gap-6 mb-5  ">
        <div className=" xl:hidden max-w-md mx-auto">
          <div className="cards_body">
            <img src={imgone} alt="" className="mb-10   " />
          </div>
        </div>
        {/* cards-2 */}
        <div className="xl:hidden max-w-md mx-auto ">
          <div className="cards_body text-left">
            <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932]">
              Select based on Interests, Location, and other pertinent filters.
            </h1>
            <p className="text-[18px] font-normal leading-[27px]">
            Discover your life partner on our matrimonial website, where
            interests align and love blossoms. Tailored to your location and
            preferences, find meaningful connections that last a lifetime
            </p>
          </div>
        </div>
      </div>

      {/* section-2 */}
      <div data-aos="fade-left"  data-aos-duration="1500" className="md:flex sec  items-center justify-between gap-6 flex-row-reverse mb-5   ">
        {/* cards-3 */}
        <div className="xl:hidden max-w-md mx-auto">
          <div className="cards_body">
            <img src={imgTwo} alt="" className="mb-10 " />
          </div>
        </div>
        {/* cards-4 */}
        <div className="xl:hidden max-w-md mx-auto">
          <div className="cards_body text-left md:text-right ">
            <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932]">
              Engage with your matches in the manner that suits you best
            </h1>
            <p className="text-[18px] font-normal leading-[27px]">
            Discover your life partner on our matrimonial website, where
            interests align and love blossoms. Tailored to your location and
            preferences, find meaningful connections that last a lifetime
            </p>
          </div>
        </div>
      </div>
      {/* section-3 */}
      <div data-aos="fade-right" data-aos-duration="1500" className="md:flex sec items-center justify-between gap-6 mb-10  ">
        {/* cards-5 */}
        <div className="xl:hidden max-w-md mx-auto ">
          <div className="cards_body">
            <img src={imgThree} alt="" className="mb-10   " />
          </div>
        </div>
        {/* cards-6 */}
        <div className="xl:hidden max-w-md mx-auto">
          <div className="cards_body text-left">
            <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932]">
              Personalized match suggestions generated by AI to align with your
              preferences
            </h1>
            <p className="text-[18px] font-normal leading-[27px]">
            Communicate on your terms with potential matches on our matrimonial
            website, Matrimony. Whether it is through messages, chats, or video
            calls, forge genuine connections in a way that feels comfortable for
            you.
            </p>
          </div>
        </div>

        {/* cards-end */}
      </div>
    </div>
  );
};

export default HowItWork;
